name: flutter_website
version: 1.0.0+1
publish_to: none
description: Website Flutter (DataTables).
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  syncfusion_flutter_datagrid: ^22.2.5
  get: 4.6.5
  flutter: 
    sdk: flutter
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1
  loading_animation_widget: ^1.2.0+4
  flutter_screenutil: ^5.8.4
  syncfusion_flutter_core: ^22.2.5

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

